### ISSUE TITLE
projects tatus

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [jschlatow/taskopen#110]
Dear ValiValpas,

could you please give a short official description about the status of the project?

It looks inactive. Are there plans for the future? Or are you aware of more up-to-date forks of your project?

**Comment by ValiValpas** [comment]
@buhtz, sure. You're right, it looks pretty inactive, which is due to several reasons:

1. Feature-wise, I consider taskopen as stable. I'm using it almost every day and thus maintaining its compatibility with current taskwarrior versions.
2. Taskopen reached a point where adding more features becomes increasingly difficult not only w.r.t. implementation but also w.r.t. usability. It already incorporates a bunch of features which, I suppose, nobody is using because they are not easily accessible. It often requires in-depth understanding of how taskopen works in order to do fancy things with it. 
3. The obvious next step in my mind is streamlining the command line interface in order to make all features easily and intuitively accessible. However, this is a big step which needs careful planning. I have some rough ideas about this which I haven't been able to write down yet due to limited time and personal priorities (see 1.). However, I'll be happy to pick this up again if current and prospective users are particularly interested (and hopefully contributing).

**Comment by jschlatow** [comment]
The rewrite is currently in alpha stage and can be found on the staging branch. Please have a look at the [wiki](https://github.com/jschlatow/taskopen/wiki/2.0) for a first draft of its documentation.
