### ISSUE TITLE
Archlinux: allow taskopen with task-dev

### ISSUE THREAD

**Issue by AdrienLemaire** [jschlatow/taskopen#118]
I want to use task version 2.6, which is made available by the arch linux aur package task-dev.

```console
$ yay -Qs task
local/task-dev 2.6.0-1
    A command-line todo list manager

$ task --version
2.6.0

$ yay -S taskopen
:: Checking for conflicts...
:: Checking for inner conflicts...

==> Package conflicts found:
 -> Installing task will remove: task-dev (task)

==> Conflicting packages will have to be confirmed manually

[Repo: 2]  perl-json-2.97001-1  task-2.5.1-2
[Aur: 1]  taskopen-1.1.4-1
```

But taskopen wants to install task-2.5, which conflicts with task-dev.
The [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=taskopen) only asks for `task>=2.4.0`, so this issue is strange.

**Comment by ValiValpas** [comment]
@Fandekasp this is an archlinux-specific issue, which is why I edited the title.

The reason why this happens is the version dependency. As you already mentioned, taskopen asks for `task>=2.4.0`. However, task-dev, only has `provides=task` without any version. As written in the [ArchWiki](https://wiki.archlinux.org/index.php/PKGBUILD#provides), alternative packages should also mention the package version they provide.

As both, taskopen and task-dev, are AUR packages, you can simply modify one of the PKGBUILDs, i.e. either removing the version dependency from taskopen or adding the version to task-dev.
